### ISSUE TITLE
[graphviz] Please enable graphviz customization interface or options tweaking resulting graph

### ISSUE THREAD

**Issue by sin-diesel** [rohaquinlop/automathon#4]
I've used the tool to generate a cartesian product of 3 finite automata, but the resulting graph is huge and when I try to view the picture, it becomes problematic to understand what is happening because the font is very small and the graph nodes themselves are too huge. It would be great if we had the option to select those graph parameters, or even better, introduce some python graphviz interface to be able to configure the graph plot settings to our preferences.

**Comment by sin-diesel** [comment]
I'll also attach the graph
![Pipe * Reader * writer visualization gv](https://github.com/rohaquinlop/automathon/assets/48734918/42b28768-bd8c-4f51-8642-dea887240881)

**Comment by rohaquinlop** [comment]
Hey @sin-diesel thank you for using automathon, I'm gonna be working on it!

**Comment by rohaquinlop** [comment]
Already created new version `0.0.13` you can update and test it @sin-diesel !
